# Generated by Django 5.2.1 on 2025-05-15 12:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('plant_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=10)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('growth_rate', models.CharField(max_length=50)),
                ('max_height', models.CharField(max_length=50)),
                ('flower_color', models.CharField(blank=True, max_length=50, null=True)),
                ('foliage_color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='plant_thumbnails/')),
                ('min_temperature', models.IntegerField()),
                ('max_temperature', models.IntegerField()),
                ('sunlight_hours', models.IntegerField()),
                ('sunlight_type', models.CharField(max_length=50)),
                ('soil_type', models.CharField(max_length=50)),
                ('ph_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ph_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('humidity_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('watering_frequency', models.CharField(max_length=50)),
                ('fertilizing_frequency', models.CharField(max_length=50)),
                ('pruning_frequency', models.CharField(max_length=50)),
                ('special_care_instructions', models.TextField(blank=True)),
                ('toxic_to_pets', models.BooleanField(default=False)),
                ('toxic_to_humans', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('affiliate_link', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to='shopping_images/')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantapp.plant')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantapp.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('water', 'Water'), ('fertilize', 'Fertilize'), ('prune', 'Prune'), ('repot', 'Repot'), ('check', 'Check for pests')], max_length=10)),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantapp.userplant')),
            ],
        ),
    ]
