# Generated by Django 5.2.1 on 2025-05-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='flower_color',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='max_temperature',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='min_temperature',
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
