# Generated by Django 5.2.1 on 2025-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0002_remove_plant_flower_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Indoor/Outdoor')], max_length=10),
        ),
    ]
