# Generated by Django 5.2.1 on 2025-05-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0004_alter_plant_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, upload_to='plant_images/'),
        ),
    ]
