# Generated by Django 5.2.1 on 2025-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='watering_frequency',
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_frequency_days',
            field=models.IntegerField(default=7, help_text='Number of days between waterings'),
        ),
    ]
